# Generated by Django 4.1.3 on 2022-11-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=200)),
                ('pizza_ID', models.CharField(max_length=200)),
                ('pizza_topping', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=200)),
                ('topping_ID', models.CharField(max_length=200)),
            ],
        ),
    ]
